using UnityEngine;

namespace PaintBucketSim.Configs
{
    [CreateAssetMenu(
        fileName = "GpuDfsphSolverConfig",
        menuName = "Paint Bucket Sim/GPU DFSPH Solver Config")]
    public sealed class GpuDfsphSolverConfig : ScriptableObject
    {
        [Header("Lifecycle")]
        public bool enableGpuDfsph = true;
        public bool logLifecycle = true;

        [Header("Compute Shader")]
        public ComputeShader dfsphCompute;

        [Header("Particle Limits")]
        [Min(128)]
        public int maxParticles = 10000;

        [Header("Time Step")]
        [Min(0.0001f)]
        public float maxDt = 1.0f / 60.0f;

        [Range(1, 8)]
        public int substeps = 2;

        [Header("DFSPH Core")]
        [Min(1.0f)]
        public float restDensity = 1000.0f;

        [Min(0.0001f)]
        public float particleRadius = 0.015f;

        [Min(0.0001f)]
        public float supportRadius = 0.045f;

        [Range(1, 20)]
        public int densitySolverIterations = 3;

        [Range(0, 4)]
        public int safetyMaxDensityIterations = 3;

        [Range(1, 20)]
        public int divergenceSolverIterations = 3;

        [Header("Stability")]
        [Min(0.0f)]
        public float velocityDampingPerSecond = 0.05f;

        [Min(0.1f)]
        public float maxParticleSpeed = 8.0f;

        [Header("Neighbor Search")]
        [Min(0.001f)]
        public float gridCellSize = 0.045f;

        public Vector3 gridOriginWorld = new Vector3(-1.44f, 2.5f, -1.44f);

        public Vector3Int gridResolution = new Vector3Int(64, 64, 64);

        [Header("Neighbor Grid Tracking")]
        public bool centerNeighborGridOnBucket = true;
        public Vector3 neighborGridCenterOffset = Vector3.zero;

        [Header("GPU Neighbor Search - Fixed Bucket Grid")]
        public bool enableNeighborSearch = true;

        [Tooltip("Maximum number of particles stored per grid cell in the fixed-bucket neighbor grid.")]
        [Min(4)]
        public int maxParticlesPerCell = 64;

        [Tooltip("If true, particles outside the neighbor grid are ignored by neighbor search.")]
        public bool discardParticlesOutsideGrid = true;

        [Tooltip("Debug kernel that counts neighbors for every particle.")]
        public bool enableNeighborCountDebug = false;

        [Header("DFSPH Density Computation")]
        public bool enableDensityComputation = true;

        [Tooltip("Clamp density to avoid invalid values during early debugging.")]
        [Min(1.0f)]
        public float minDensityClamp = 1.0f;

        [Tooltip("Maximum density clamp for debugging. Use a high value.")]
        [Min(1.0f)]
        public float maxDensityClamp = 5000.0f;

        [Tooltip("If true, KComputeDensity also writes NeighborCount, so the separate debug neighbor count pass can be disabled later.")]
        public bool densityKernelWritesNeighborCount = true;

        [Header("DFSPH Alpha / Pressure Factor")]
        public bool enableAlphaComputation = true;

        [Tooltip("Minimum denominator used when computing alpha. Prevents division by zero near free surfaces.")]
        [Min(1e-12f)]
        public float alphaDenominatorEpsilon = 1e-6f;

        [Tooltip("Maximum alpha clamp for early stability.")]
        [Min(0.0001f)]
        public float maxAlpha = 100000.0f;

        [Tooltip("If neighbor count is below this value, alpha is damped to reduce free-surface explosions.")]
        [Min(0)]
        public int minNeighborsForFullAlpha = 8;

        [Range(0.0f, 1.0f)]
        public float lowNeighborAlphaDamping = 0.25f;

        [Header("DFSPH Divergence Solver")]
        public bool enableDivergenceSolve = true;

        [Tooltip("Scales the divergence error before converting it into pressure.")]
        [Min(0.0f)]
        public float divergenceErrorScale = 1.0f;

        [Tooltip("Strength of the velocity correction generated by the divergence pressure.")]
        [Min(0.0f)]
        public float divergenceCorrectionStrength = 0.4f;

        [Tooltip("Clamp for divergence pressure factor.")]
        [Min(0.0f)]
        public float maxDivergencePressure = 3000.0f;

        [Tooltip("Clamp for velocity correction per particle per iteration.")]
        [Min(0.01f)]
        public float maxDivergenceVelocityCorrection = 0.4f;

        [Tooltip("Use only positive compression errors. Recommended for stability.")]
        public bool clampDivergenceToCompressionOnly = true;

        [Tooltip("Flip sign of divergence error if the correction visibly increases compression.")]
        public bool invertDivergenceErrorSign = false;

        [Header("DFSPH Advection")]
        public bool enableParticleAdvection = true;

        [Header("DFSPH Density Solver")]
        public bool enableDensitySolve = true;

        [Tooltip("Scales the predicted density error before converting it into pressure.")]
        [Min(0.0f)]
        public float densityErrorScale = 1.0f;

        [Tooltip("Strength of the velocity correction generated by the density pressure.")]
        [Min(0.0f)]
        public float densityCorrectionStrength = 0.4f;

        [Tooltip("Clamp for density pressure factor.")]
        [Min(0.0f)]
        public float maxDensityPressure = 3000.0f;

        [Tooltip("Clamp for density velocity correction per particle per iteration.")]
        [Min(0.01f)]
        public float maxDensityVelocityCorrection = 0.4f;

        [Tooltip("Use only positive compression errors. Recommended for stability.")]
        public bool clampDensityToCompressionOnly = true;

        [Tooltip("Flip sign of density error if the correction visibly increases compression.")]
        public bool invertDensityErrorSign = false;

        [Header("DFSPH Bucket SDF Boundary")]
        public bool enableBucketSdfBoundary = true;

        [Tooltip("Apply analytic bucket boundary after particle advection.")]
        public bool applyBucketBoundaryAfterAdvection = true;

        [Tooltip("Number of boundary projection passes per substep. Start with 1.")]
        [Range(1, 4)]
        public int bucketBoundaryPasses = 2;

        [Tooltip("Small safety distance from the wall and bottom.")]
        [Min(0.0f)]
        public float bucketBoundaryPadding = 0.002f;

        [Tooltip("How strongly positions are projected back into the bucket. 1 = full correction.")]
        [Range(0.0f, 1.0f)]
        public float bucketBoundaryPositionCorrectionStrength = 1.0f;

        [Tooltip("How strongly velocity is corrected when moving into the wall.")]
        [Range(0.0f, 1.0f)]
        public float bucketBoundaryVelocityCorrectionStrength = 0.7f;

        [Tooltip("Normal bounce. For paint, keep near zero.")]
        [Range(0.0f, 1.0f)]
        public float bucketBoundaryRestitution = 0.0f;

        [Tooltip("Tangential damping against the wall.")]
        [Range(0.0f, 1.0f)]
        public float bucketBoundaryFriction = 0.35f;

        public bool bucketBoundaryTopOpen = true;
        public bool bucketBoundaryEnableSideWalls = true;
        public bool bucketBoundaryEnableBottom = true;

        [Header("DFSPH Moving Bucket Wall Coupling")]
        public bool enableMovingBucketWallVelocity = true;

        [Tooltip("Apply wall velocity coupling before neighbor search and pressure solve.")]
        public bool applyMovingBucketVelocityBeforeSolve = true;

        [Tooltip("Use bucket linear and angular velocity during boundary collision response.")]
        public bool useMovingWallVelocityInBoundary = true;

        [Range(0.0f, 1.0f)]
        public float movingWallVelocityStrength = 0.8f;

        [Min(0.01f)]
        public float maxMovingWallVelocity = 4.0f;

        [Min(0.01f)]
        public float maxPreSolveWallVelocityCorrection = 0.3f;

        [Tooltip("Extra distance near the wall where pre-solve velocity correction starts.")]
        [Min(0.0f)]
        public float preSolveWallInfluenceDistance = 0.03f;

        [Range(0.0f, 1.0f)]
        public float preSolveWallVelocityCorrectionStrength = 0.4f;


        [Header("DFSPH Paint Material - Viscosity / Cohesion")]
        public bool enablePaintMaterialModel = true;

        [Tooltip("XSPH viscosity strength. Higher values make paint move more like a thick fluid.")]
        [Range(0.0f, 1.0f)]
        public float xsphViscosityStrength = 0.12f;

        [Tooltip("Maximum velocity change from viscosity/cohesion per pass.")]
        [Min(0.001f)]
        public float maxPaintMaterialVelocityCorrection = 0.15f;

        [Tooltip("Cohesion strength between nearby particles. Helps paint stay together.")]
        [Range(0.0f, 2.0f)]
        public float cohesionStrength = 0.25f;

        [Tooltip("Distance factor below which cohesion becomes stronger. Relative to support radius.")]
        [Range(0.05f, 1.0f)]
        public float cohesionDistanceFactor = 0.65f;

        [Tooltip("Damps isolated fast particles to reduce spray-like behavior.")]
        [Range(0.0f, 1.0f)]
        public float antiSprayDamping = 0.15f;

        [Tooltip("Neighbor count below which anti-spray damping starts.")]
        [Min(0)]
        public int antiSprayNeighborThreshold = 6;

        [Header("DFSPH Paint Material - Wall Adhesion")]
        public bool enableWallAdhesionDamping = true;

        [Tooltip("Distance from bucket wall where adhesion damping is applied.")]
        [Min(0.0f)]
        public float wallAdhesionDistance = 0.025f;

        [Tooltip("Tangential velocity damping near wall.")]
        [Range(0.0f, 1.0f)]
        public float wallTangentialDamping = 0.35f;

        [Tooltip("Normal velocity damping near wall.")]
        [Range(0.0f, 1.0f)]
        public float wallNormalDamping = 0.25f;

        [Tooltip("Small attraction toward wall for wet paint behavior. Keep low.")]
        [Range(0.0f, 1.0f)]
        public float wallAdhesionAttraction = 0.05f;

        [Header("DFSPH Bucket Frame Transport / Anti-Collapse")]
        public bool enableBucketFrameTransport = true;

        [Tooltip("Moves particles with the bucket transform delta before pressure solve. Useful for kinematic/parent-driven bucket motion.")]
        [Range(0.0f, 1.0f)]
        public float bucketFramePositionTransportStrength = 0.85f;

        [Tooltip("Adds part of the bucket frame transport velocity to particles.")]
        [Range(0.0f, 1.0f)]
        public float bucketFrameVelocityTransportStrength = 0.25f;

        [Tooltip("Clamp for velocity added by bucket frame transport.")]
        [Min(0.01f)]
        public float maxBucketFrameTransportVelocity = 3.0f;

        [Tooltip("Ignore very small bucket transform changes.")]
        [Min(0.0f)]
        public float bucketFrameTransportMinDelta = 0.00001f;


        [Header("DFSPH Boundary-Aware Stabilization")]
        public bool enableBoundaryAwareDfsph = true;

        [Tooltip("Distance from bucket wall/bottom where boundary compensation starts.")]
        [Min(0.001f)]
        public float boundaryInfluenceDistance = 0.055f;

        [Tooltip("How much artificial boundary density is added near walls. Start low.")]
        [Range(0.0f, 2.0f)]
        public float boundaryDensityContribution = 0.65f;

        [Tooltip("Scales alpha near walls to avoid unstable pressure overreaction.")]
        [Range(0.05f, 1.0f)]
        public float boundaryAlphaScaleNearWall = 0.65f;

        [Tooltip("Adds a velocity push away from the wall when compressed or moving into wall.")]
        public bool enableBoundaryPressurePush = true;

        [Range(0.0f, 2.0f)]
        public float boundaryPressurePushStrength = 0.5f;

        [Min(0.001f)]
        public float maxBoundaryPressureVelocityCorrection = 0.25f;

        [Tooltip("Uses moving bucket wall velocity while computing wall-relative compression.")]
        public bool useMovingWallVelocityForBoundaryPush = true;

        [Tooltip("How strongly density error contributes to wall push.")]
        [Range(0.0f, 5.0f)]
        public float boundaryDensityErrorPushScale = 1.0f;


        [Header("SDF Boundary Solver V2 - Conservative Collision")]
        public bool enableConservativeSdfBoundary = true;

        public bool enableSdfPreSolveCollision = true;

        [Tooltip("Extra distance near wall where incoming normal velocity is removed before neighbor search.")]
        [Min(0.0001f)]
        public float sdfSkinDistance = 0.008f;

        [Tooltip("How strongly inward normal velocity is removed near the wall.")]
        [Range(0.0f, 1.0f)]
        public float sdfNormalVelocityRemoval = 1.0f;

        [Tooltip("Tangential damping near SDF wall. Keep low for paint inside bucket.")]
        [Range(0.0f, 1.0f)]
        public float sdfTangentialFriction = 0.08f;

        [Tooltip("Maximum velocity correction by pre-solve SDF per substep.")]
        [Min(0.0001f)]
        public float maxSdfPreSolveVelocityCorrection = 0.45f;

        [Tooltip("Maximum position correction by SDF projection per substep.")]
        [Min(0.0001f)]
        public float maxSdfPositionCorrectionPerStep = 0.003f;

        [Tooltip("Final SDF projection strength. Lower values prevent wall from acting like a piston.")]
        [Range(0.0f, 1.0f)]
        public float sdfProjectionStrength = 0.25f;

        [Tooltip("Use moving bucket wall velocity when resolving SDF boundary.")]
        public bool sdfUseMovingWallVelocity = true;


        [Header("GPU Boundary Particles")]
        public bool enableGpuBoundaryParticles = true;

        [Tooltip("Maximum boundary particles uploaded to GPU.")]
        [Min(0)]
        public int maxBoundaryParticles = 50000;

        [Tooltip("Maximum boundary particles stored per boundary grid cell.")]
        [Min(4)]
        public int maxBoundaryParticlesPerCell = 128;

        [Tooltip("If true, boundary particles outside the grid are ignored and counted.")]
        public bool discardBoundaryParticlesOutsideGrid = true;

        [Tooltip("Print boundary grid diagnostics every N frames. 0 disables logging.")]
        [Min(0)]
        public int boundaryGridStatsLogEveryNFrames = 60;

        [Tooltip("Scales exported boundary psi. Keep 1 initially.")]
        [Min(0.0f)]
        public float boundaryPsiScale = 1.0f;

        [Tooltip("Fallback boundary radius if BoundarySystem does not provide one.")]
        [Min(0.0001f)]
        public float fallbackBoundaryParticleRadius = 0.012f;


        [Header("DFSPH Boundary Particles - Density / Alpha")]
        public bool enableBoundaryParticleDensity = true;

        [Range(0.0f, 3.0f)]
        public float boundaryDensityStrength = 0.45f;

        [Min(0.0f)]
        public float maxBoundaryDensityContribution = 650.0f;

        public bool enableBoundaryParticleAlpha = true;

        [Range(0.0f, 3.0f)]
        public float boundaryAlphaStrength = 0.65f;

        [Min(0)]
        public int minBoundaryNeighborsForFullSupport = 6;

        [Range(0.0f, 1.0f)]
        public float lowBoundaryNeighborDamping = 0.35f;

        [Tooltip("If true, KComputeDensity writes boundary neighbor count and boundary density contribution for debugging.")]
        public bool writeBoundaryDensityDebug = true;


        [Header("DFSPH Boundary Particles - Pressure Correction")]
        public bool enableBoundaryDivergencePressure = true;

        [Range(0.0f, 3.0f)]
        public float boundaryDivergencePressureStrength = 0.55f;

        public bool enableBoundaryDensityPressure = true;

        [Range(0.0f, 3.0f)]
        public float boundaryDensityPressureStrength = 0.65f;

        [Min(0.0f)]
        public float maxBoundaryDivergenceVelocityCorrection = 0.20f;

        [Min(0.0f)]
        public float maxBoundaryDensityVelocityCorrection = 0.25f;

        [Tooltip("Use boundary particle velocity when computing divergence against moving bucket walls.")]
        public bool useBoundaryVelocityInPressure = true;

        [Tooltip("Optional normal filter. Keep false until normals are verified.")]
        public bool enableBoundaryNormalFiltering = false;

        [Range(-1.0f, 1.0f)]
        public float boundaryNormalMinDot = -0.25f;

        [Tooltip("Debug multiplier. Keep 1.0 initially.")]
        [Range(0.0f, 3.0f)]
        public float boundaryPressureDebugScale = 1.0f;


        [Header("DFSPH Boundary Particles - Collision PreSolve")]
        public bool enableBoundaryParticleCollisionPreSolve = true;

        [Tooltip("Collision distance as multiplier of support radius.")]
        [Range(0.05f, 1.0f)]
        public float boundaryCollisionDistanceFactor = 0.45f;

        [Tooltip("Removes inward velocity relative to boundary normal.")]
        [Range(0.0f, 1.0f)]
        public float boundaryCollisionNormalVelocityRemoval = 1.0f;

        [Tooltip("Tangential damping near boundary particles.")]
        [Range(0.0f, 1.0f)]
        public float boundaryCollisionTangentialFriction = 0.08f;

        [Tooltip("Maximum velocity correction per substep from boundary-particle collision.")]
        [Min(0.0f)]
        public float maxBoundaryCollisionVelocityCorrection = 0.18f;

        [Tooltip("Very small position correction if particle is too close to boundary.")]
        [Min(0.0f)]
        public float maxBoundaryCollisionPositionCorrection = 0.0015f;

        [Tooltip("Use boundary particle velocity for moving bucket collision.")]
        public bool useBoundaryVelocityInCollision = true;

        [Tooltip("Only collide with boundary particles whose normal faces the fluid particle.")]
        public bool enableBoundaryCollisionNormalFilter = true;

        [Range(-1.0f, 1.0f)]
        public float boundaryCollisionNormalMinDot = 0.15f;

        public int GridCellCount =>
            Mathf.Max(1, gridResolution.x) *
            Mathf.Max(1, gridResolution.y) *
            Mathf.Max(1, gridResolution.z);

        private void OnValidate()
        {
            maxParticles = Mathf.Max(128, maxParticles);
            restDensity = Mathf.Max(1.0f, restDensity);
            particleRadius = Mathf.Max(0.0001f, particleRadius);
            supportRadius = Mathf.Max(particleRadius * 2.0f, supportRadius);
            gridCellSize = Mathf.Max(0.001f, gridCellSize);

            gridResolution.x = Mathf.Max(1, gridResolution.x);
            gridResolution.y = Mathf.Max(1, gridResolution.y);
            gridResolution.z = Mathf.Max(1, gridResolution.z);

            if (maxParticlesPerCell < 4)
                maxParticlesPerCell = 4;

            // For the 27-cell neighbor search to be correct,
            // gridCellSize should be at least supportRadius.
            if (gridCellSize < supportRadius)
                gridCellSize = supportRadius;

            if (minDensityClamp < 1.0f)
                minDensityClamp = 1.0f;

            if (maxDensityClamp < minDensityClamp)
                maxDensityClamp = minDensityClamp;

            if (alphaDenominatorEpsilon < 1e-12f)
                alphaDenominatorEpsilon = 1e-12f;

            if (maxAlpha < 0.0001f)
                maxAlpha = 0.0001f;

            if (minNeighborsForFullAlpha < 0)
                minNeighborsForFullAlpha = 0;

            lowNeighborAlphaDamping = Mathf.Clamp01(lowNeighborAlphaDamping);

            if (divergenceErrorScale < 0.0f)
                divergenceErrorScale = 0.0f;

            if (divergenceCorrectionStrength < 0.0f)
                divergenceCorrectionStrength = 0.0f;

            if (maxDivergencePressure < 0.0f)
                maxDivergencePressure = 0.0f;

            if (maxDivergenceVelocityCorrection < 0.01f)
                maxDivergenceVelocityCorrection = 0.01f;

            if (densityErrorScale < 0.0f)
                densityErrorScale = 0.0f;

            if (densityCorrectionStrength < 0.0f)
                densityCorrectionStrength = 0.0f;

            if (maxDensityPressure < 0.0f)
                maxDensityPressure = 0.0f;

            if (maxDensityVelocityCorrection < 0.01f)
                maxDensityVelocityCorrection = 0.01f;


            bucketBoundaryPasses = Mathf.Clamp(bucketBoundaryPasses, 1, 4);

            if (bucketBoundaryPadding < 0.0f)
                bucketBoundaryPadding = 0.0f;

            bucketBoundaryPositionCorrectionStrength =
                Mathf.Clamp01(bucketBoundaryPositionCorrectionStrength);

            bucketBoundaryVelocityCorrectionStrength =
                Mathf.Clamp01(bucketBoundaryVelocityCorrectionStrength);

            bucketBoundaryRestitution =
                Mathf.Clamp01(bucketBoundaryRestitution);

            bucketBoundaryFriction =
                Mathf.Clamp01(bucketBoundaryFriction);


            movingWallVelocityStrength = Mathf.Clamp01(movingWallVelocityStrength);

            if (maxMovingWallVelocity < 0.01f)
                maxMovingWallVelocity = 0.01f;

            if (maxPreSolveWallVelocityCorrection < 0.01f)
                maxPreSolveWallVelocityCorrection = 0.01f;

            if (preSolveWallInfluenceDistance < 0.0f)
                preSolveWallInfluenceDistance = 0.0f;

            preSolveWallVelocityCorrectionStrength =
                Mathf.Clamp01(preSolveWallVelocityCorrectionStrength);

            xsphViscosityStrength = Mathf.Clamp01(xsphViscosityStrength);

            if (maxPaintMaterialVelocityCorrection < 0.001f)
                maxPaintMaterialVelocityCorrection = 0.001f;

            cohesionStrength = Mathf.Clamp(cohesionStrength, 0.0f, 2.0f);
            cohesionDistanceFactor = Mathf.Clamp(cohesionDistanceFactor, 0.05f, 1.0f);
            antiSprayDamping = Mathf.Clamp01(antiSprayDamping);

            if (antiSprayNeighborThreshold < 0)
                antiSprayNeighborThreshold = 0;

            if (wallAdhesionDistance < 0.0f)
                wallAdhesionDistance = 0.0f;

            wallTangentialDamping = Mathf.Clamp01(wallTangentialDamping);
            wallNormalDamping = Mathf.Clamp01(wallNormalDamping);
            wallAdhesionAttraction = Mathf.Clamp01(wallAdhesionAttraction);

            bucketFramePositionTransportStrength = Mathf.Clamp01(bucketFramePositionTransportStrength);

            bucketFrameVelocityTransportStrength = Mathf.Clamp01(bucketFrameVelocityTransportStrength);

            if (maxBucketFrameTransportVelocity < 0.01f)
                maxBucketFrameTransportVelocity = 0.01f;

            if (bucketFrameTransportMinDelta < 0.0f)
                bucketFrameTransportMinDelta = 0.0f;


            if (boundaryInfluenceDistance < 0.001f)
                boundaryInfluenceDistance = 0.001f;

            boundaryDensityContribution =
                Mathf.Clamp(boundaryDensityContribution, 0.0f, 2.0f);

            boundaryAlphaScaleNearWall =
                Mathf.Clamp(boundaryAlphaScaleNearWall, 0.05f, 1.0f);

            boundaryPressurePushStrength =
                Mathf.Clamp(boundaryPressurePushStrength, 0.0f, 2.0f);

            if (maxBoundaryPressureVelocityCorrection < 0.001f)
                maxBoundaryPressureVelocityCorrection = 0.001f;

            boundaryDensityErrorPushScale =
                Mathf.Clamp(boundaryDensityErrorPushScale, 0.0f, 5.0f);

            if (sdfSkinDistance < 0.0001f)
                sdfSkinDistance = 0.0001f;

            sdfNormalVelocityRemoval =
                Mathf.Clamp01(sdfNormalVelocityRemoval);

            sdfTangentialFriction =
                Mathf.Clamp01(sdfTangentialFriction);

            if (maxSdfPreSolveVelocityCorrection < 0.0001f)
                maxSdfPreSolveVelocityCorrection = 0.0001f;

            if (maxSdfPositionCorrectionPerStep < 0.0001f)
                maxSdfPositionCorrectionPerStep = 0.0001f;

            sdfProjectionStrength = Mathf.Clamp01(sdfProjectionStrength);

            if (maxBoundaryParticles < 0)
                maxBoundaryParticles = 0;

            if (maxBoundaryParticlesPerCell < 4)
                maxBoundaryParticlesPerCell = 4;

            if (boundaryGridStatsLogEveryNFrames < 0)
                boundaryGridStatsLogEveryNFrames = 0;

            if (boundaryPsiScale < 0.0f)
                boundaryPsiScale = 0.0f;

            if (fallbackBoundaryParticleRadius < 0.0001f)
                fallbackBoundaryParticleRadius = 0.0001f;

            boundaryDensityStrength = Mathf.Clamp(boundaryDensityStrength, 0.0f, 3.0f);

            if (maxBoundaryDensityContribution < 0.0f)
                maxBoundaryDensityContribution = 0.0f;

            boundaryAlphaStrength =
                Mathf.Clamp(boundaryAlphaStrength, 0.0f, 3.0f);

            if (minBoundaryNeighborsForFullSupport < 0)
                minBoundaryNeighborsForFullSupport = 0;

            lowBoundaryNeighborDamping =
                Mathf.Clamp01(lowBoundaryNeighborDamping);

            boundaryDivergencePressureStrength = Mathf.Clamp(boundaryDivergencePressureStrength, 0.0f, 3.0f);

            boundaryDensityPressureStrength =
                Mathf.Clamp(boundaryDensityPressureStrength, 0.0f, 3.0f);

            if (maxBoundaryDivergenceVelocityCorrection < 0.0f)
                maxBoundaryDivergenceVelocityCorrection = 0.0f;

            if (maxBoundaryDensityVelocityCorrection < 0.0f)
                maxBoundaryDensityVelocityCorrection = 0.0f;

            boundaryNormalMinDot =
                Mathf.Clamp(boundaryNormalMinDot, -1.0f, 1.0f);

            boundaryPressureDebugScale =
                Mathf.Clamp(boundaryPressureDebugScale, 0.0f, 3.0f);

            boundaryCollisionDistanceFactor = Mathf.Clamp(boundaryCollisionDistanceFactor, 0.05f, 1.0f);

            boundaryCollisionNormalVelocityRemoval = Mathf.Clamp01(boundaryCollisionNormalVelocityRemoval);

            boundaryCollisionTangentialFriction = Mathf.Clamp01(boundaryCollisionTangentialFriction);

            if (maxBoundaryCollisionVelocityCorrection < 0.0f)
                maxBoundaryCollisionVelocityCorrection = 0.0f;

            if (maxBoundaryCollisionPositionCorrection < 0.0f)
                maxBoundaryCollisionPositionCorrection = 0.0f;

            boundaryCollisionNormalMinDot = Mathf.Clamp(boundaryCollisionNormalMinDot, -1.0f, 1.0f);
        }
    }
}